docs_dir: 
site_name: Submin

nav:
  - Home: index.md
  - "Visão de produto":
    - visao/cenario.md
    - visao/solucao.md
    - visao/estrategias.md
    - visao/cronograma.md

theme:
  name: material
  palette:
    primary: black
    accent: red

  navigation_depth: 2

  language: pt-BR

  features:
    - navigation.tabs
    - navigation.expand
    - navigation.top

